### ISSUE TITLE
Define service types

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/product-development#10]
If we're going to do service-oriented architecture well, we should start thinking about what makes a service, an appropriate scope for service responsibilities, and how they interact.

In thinking about a high-level design pattern to apply, I came up with three types for services. Each type has its own unique purpose and relation to other types, and all services would belong to one and only one type.

The types of services are:

1. Core
1. Interface
1. Adapter

#### Core
Core services manage internal data and business logic. They are networked and expose a secure RESTful JSON API via HTTP.

Examples: Identity Management, Feedback API.

#### Interface
Interface services provide a UI and front-end behavior (validations, basic UX) for interacting with one or more core services. They range from command-line tools to full web or mobile apps.

Examples: Command-Line Task List, Admissions Dashboard.

#### Adapter
Adapter services provide a bridge between internal core services or between core services and third-party software. They are purpose-built to link data between two APIs and create a dependency buffer between them, thus insulating services against external changes.

Examples: Slack Integration for Pairing Service, Data Sync between Survey Software and Core Metrics Service, Web Hook on GitHub to Capture Student Submissions and Update Challenge Service

**Comment by tannerwelsh** [comment]
@jeffreywescott how does this fit with how you envision services? Too much design? Too little?

**Comment by jeffreywescott** [comment]
I like this!

My only dispute is minor: that core services expose a "secure RESTful JSON API via HTTP". I can envision a case where a core service only provides a web-sockets interface, or a set of APIs that are not _only_ RESTFUL.

**Comment by jeffreywescott** [comment]
(extracted from original feedback in #2 from @tannerwelsh):

To keep focus on core vs. auxiliary services, thinking about what can be accomplished by third-party tools vs. what should be part of our system. Here's how I'd break it down:

**Core services**
- identity
- admissions
- feedback
- pairing

**Auxiliary services** (consider using third party software)
- group collaboration
- task list
- surveys
- collaborative decision making

**Not sure whether core/external**
- alumni portal

**Comment by tannerwelsh** [comment]
Re: your dispute @jeffreywescott, I agree. Maybe we can simplify to "secure web API"? And then add some entries to Best Practices for HTTPS API design & WebSocket API design?

**Comment by jeffreywescott** [comment]
Sure. Tracked here: https://app.asana.com/0/47034315776876/65444446702306

**Comment by jeffreywescott** [comment]
Closing b/c of #19
