### ISSUE TITLE
add a section for "standard toolkit"

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/product-development#12]
(extracted from #2 from @tannerwelsh)

Another section that could be useful is a "Standard Toolkit". I'd see this composed of:

- Service generator 
  <br>Boilerplate app for rapid prototyping, follows our established best practices/global requirements and easily integrates into the SOA
- Dev env manager 
  <br>Like boxen https://github.com/boxen/our-boxen/

**Comment by jeffreywescott** [comment]
I like the "service generator" idea. We could probably use something like [Yeoman](http://yeoman.io/) for that. Thoughts?

As for Boxen, I vote _no_. Strongly. I'd rather use [Docker](https://www.docker.com/) and [Boot2Docker](http://boot2docker.io/).

**Comment by tannerwelsh** [comment]
Haven't worked with Yeoman, but it looks like the right tool for the job. Adding a task for myself to explore more.

I've worked with Docker a bit, but not Boot2Docker. Will play with that too. What have you used them for in the past?

**Comment by jeffreywescott** [comment]
The thing about Docker and Boot2Docker is that you get the same environment in both development and production. It seems to be "the future" of DevOps, and a good thing to train people on. Boot2Docker just makes it easy to run Docker containers on your desktop.

So, my idea is that we come up with a set of Docker images that we can use for various aspects of learning guild ... like an image for working on challenges, etc. Students will just run boot2docker with our image and don't have to worry about Xcode developer tools, homebrew, or any other such nonsense. The environment will be self-contained.

**Comment by tannerwelsh** [comment]
I like it. At the very least it could function as a useful intermediary stage between working with in-browser IDEs and a "real" local dev environment.

**Comment by jeffreywescott** [comment]
Oh ... just wait until you see what I've got cooking for that. Seriously. Very cool.

**Comment by tannerwelsh** [comment]
[interest piqued]

**Comment by tannerwelsh** [comment]
Looks like [Docker Toolbox](https://www.docker.com/docker-toolbox) has replaced Boot2Docker.

**Comment by jeffreywescott** [comment]
Yep. Kitematic is the "braindead" way to get started ... sorry -- forgot that boot2docker went away.

**Comment by tannerwelsh** [comment]
No worries. Just starting to tinker with Kinematic and the docker CLI tools. So far really like the ~3 min install and shallow learning curve (so far).

**Comment by jeffreywescott** [comment]
Closing b/c of #18
