### ISSUE TITLE
other services to consider

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/product-development#14]
(extracted from #2 from @tannerwelsh)

### Other services:

- project management (likely auxiliary)
- dashboard (internal): primary UI to bind other services
- aptitude graph (internal): graph of skills/knowledge forming a "map" of what is to be learned)

**Comment by jeffreywescott** [comment]
@tannerwelsh, can you elaborate more on these and submit a PR? I'm open to additional services, but it's hard for me to suss-out what's meant by these specifically from the names and brief descriptions.

**Comment by tannerwelsh** [comment]
Sure! Added this work to a project https://app.asana.com/0/65435850287563/list

**Comment by tannerwelsh** [comment]
Closing this issue since now tracked in PRs created.
