### ISSUE TITLE
services should support learning practices and not be tied to subject being learned

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/product-development#15]
(extracted from #2 from @tannerwelsh)

Seems too strongly coupled to technical topic (programming).

**Comment by jeffreywescott** [comment]
The approach I'd like us to take is to build the best set of software the world has ever seen WRT learning _programming_, then make it more generic later after we get great at that particular topic. My hunch is that you may be right with _some_ of the services, but not others. In other words, I think there may be (in the long term) lots of services that are tailored specifically to _programming_ (e.g., the `challenge-taking` service may integrate tightly with GitHub) while other services will be more generic (e.g., the `identity management` service).

Can we just punt on this and cross the bridge when we come to it? What would resolve your tension around this, @tannerwelsh?

**Comment by tannerwelsh** [comment]
Happy to punt on this one. So long as there's clear boundaries between services, I think that resolves my tension for now.
