### ISSUE TITLE
Review & suggestions

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/product-development#2]
This is a good start. I reviewed and will put a bit more thought into changes that I'd make and submit my own PRs.

---

Seems too strongly coupled to technical topic (programming). Services should support learning practices, and not be tied to the subject being learned.

To keep focus on core vs. auxiliary services, thinking about what can be accomplished by third-party tools vs. what should be part of our system. Here's how I'd break it down:

**Core services**
- identity
- admissions
- feedback
- pairing

**Auxiliary services** (consider using third party software)
- group collaboration
- task list
- surveys
- collaborative decision making

**Not sure whether core/external**
- alumni portal

**Remove or reconsider**
- challenge authoring
- challenge taking

**Other services**
- project management (likely auxiliary)
- dashboard (internal): primary UI to bind other services
- aptitude graph (internal): graph of skills/knowledge forming a "map" of what is to be learned)

Another section that could be useful is a "Standard Toolkit". I'd see this composed of:

- Service generator
  <br>Boilerplate app for rapid prototyping, follows our established best practices/global requirements and easily integrates into the SOA
- Dev env manager
  <br>Like boxen https://github.com/boxen/our-boxen/

Like the best practices, would add these to the list:

- follow a style guide
- prefer latest releases for all dependencies
- testing:
  - unit test suite should run in < 5sec
  - write integration tests for all common use cases
  - seek at least 90% test coverage

**Comment by jeffreywescott** [comment]
Thanks for these suggestions.

For simplicity, I've broken out the individual suggestions into separate issues to be addressed independently, and will close this one.

See: #11, #12, #13, #14, and #15.

**Comment by tannerwelsh** [comment]
:+1: thanks!
