### ISSUE TITLE
Default file structure for each service type

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/product-development#20]
Services should share a conventional file structure to make it easier for developers to switch contexts and get up to speed.

Eventually these file structures should be codified in our service generator tool, but for now they could live as specifications in our Global Requirements.

First pass at draft structure:

```shell-session
bin/            # for public API executable scripts (e.g. bin/test, bin/start, bin/deploy)
lib/            # for internal library files
README.md       # orientation, installation, getting started, primary use case
CONTRIBUTING.md # how to edit/contribute
LICENSE         # self-explanatory
```

**Comment by jeffreywescott** [comment]
Thanks for this! I'll add something, and codify it with our generator(s).

I think we're likely to have _some_ variance here. For example, some services may be API-only, while others may be client-side-only. Still others may be isomorphic. So ... it might be worth calling-out that variance. I'll think on it a bit.

**Comment by jeffreywescott** [comment]
See: dbe20665ccb269a243a09a8da7cafcc29601962f

**Comment by tannerwelsh** [comment]
:+1: Thanks @jeffreywescott!
